### ISSUE TITLE
Gitlab runner very slow pulling from quay.io - need local cache

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/hgi-ansible#36] opened 2017-06-13 17:14 UTC
So far the "validate" stage of the latest CI run (internal example: https://gitlab.internal.sanger.ac.uk/hgi/hgi-systems/builds/45177) has been going for 25 minutes and 2 of the 6 jobs have not yet finished pulling the docker image from quay.io. We badly need a local docker registry / cache.

**Comment by colin-nolan** [comment] 2017-06-13 21:18
Wow, that's slow :/.

Duplicate of https://github.com/wtsi-hgi/hgi-systems/issues/21.

**Closed as completed by colin-nolan** 2017-06-13 21:18 UTC
